# Generated by Django 3.1.2 on 2020-12-19 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=20, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=20, null=True, verbose_name='Фамилия')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.studentgroup', verbose_name='Учебная группа')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
