# Generated by Django 3.1.2 on 2020-12-20 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('document', models.FileField(upload_to='', verbose_name='Документ')),
                ('status', models.CharField(choices=[('A', 'Проверен'), ('B', 'Требует исправлений'), ('C', 'Ожидает проверки')], default='C', max_length=20, verbose_name='Статус')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текст ответа')),
                ('status', models.CharField(choices=[('A', 'Проверен'), ('B', 'Требует исправлений'), ('C', 'Ожидает проверки')], default='C', max_length=20, verbose_name='Статус')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaboratoryWork.article', verbose_name='Отчет')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['-published'],
            },
        ),
    ]
