# Generated by Django 3.1.2 on 2020-12-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaboratoryWork', '0002_auto_20201220_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryStand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('key', models.CharField(max_length=50, verbose_name='Ключ')),
            ],
            options={
                'verbose_name': 'Лабораторный стенд',
                'verbose_name_plural': 'Лабораторные стенды',
            },
        ),
        migrations.AlterModelOptions(
            name='laboratorywork',
            options={'verbose_name': 'Лабораторная работа', 'verbose_name_plural': 'Лабораторные работы'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='laboratory_work',
        ),
    ]
